NguyenManhToan_SE1604_A02/Controllers/FlowerBouquetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObjects.Entities;
using Repositories.IRepositories;
using FluentValidation;
using Repositories.Repositories;
using FluentValidation.Results;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.SignalR;

namespace NguyenManhToan_SE1604_A02.Controllers
{
    public class FlowerBouquetController : BaseController
    {
        private readonly IValidator<FlowerBouquet> _validation;
        private readonly IHubContext<SignalrServer> _signalHub;


        public FlowerBouquetController(ICustomerRepository customerRepository, IOrderRepository orderRepository, IOrderDetailRepository orderDetailRepository, IFlowerBouquetRepository flowerBouquetRepository, ICategoryRepository categoryRepository, ISupplierRepository supplierRepository, IValidator<FlowerBouquet> validation, IHubContext<SignalrServer> signalHub) : base(customerRepository, orderRepository, orderDetailRepository, flowerBouquetRepository, categoryRepository, supplierRepository)
        {
            _validation = validation;
            _signalHub = signalHub;
        }


        // GET: FlowerBouquet
        public async Task<IActionResult> Index()
        {
            string userLogin = HttpContext.Session.GetString("USERLOGIN");
            if (!(await _customerRepository.IsAdmin(userLogin)))
            {
                return RedirectToAction("Index", "User");
            }
            var flowerBouquets = await _flowerBouquetRepository.GetList();
            return flowerBouquets is not null ? View(flowerBouquets.ToList()) :
                Problem("Entity set 'FuflowerBouquetManagementContext.FlowerBouquets'  is null.");
        }

        //SignalR
        [HttpGet]
        public async Task<IActionResult> GetFlowerBouquets()
        {
            var result = await _flowerBouquetRepository.GetList();
            return Ok(result);
        }

        // GET: FlowerBouquet/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                string userLogin = HttpContext.Session.GetString("USERLOGIN");
                if (!(await _customerRepository.IsAdmin(userLogin)))
                {
                    return RedirectToAction("Index", "User");
                }
                if (await _flowerBouquetRepository.GetFlowerBouquetById(id) is null)
                {
                    throw new Exception("FlowerBouquet ID is not found!!!");
                }
                var flowerBouquet = await _flowerBouquetRepository.GetFlowerBouquetById(id);
                if (flowerBouquet is null)
                {
                    throw new Exception("FlowerBouquet ID is not found!!!");
                }
                return View(flowerBouquet);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: FlowerBouquet/Create
        public async Task<IActionResult> Create()
        {
            try
            { 
                string userLogin = HttpContext.Session.GetString("USERLOGIN");
                if (!(await _customerRepository.IsAdmin(userLogin)))
                {
                    return RedirectToAction("Index", "User");
                }
                //Catch Any error
                if (TempData.TryGetValue("Errors", out var errors) && errors is string[] errorMessages)
                {
                    foreach (var errorMessage in errorMessages)
                    {
                        ModelState.AddModelError("", errorMessage);
                    }
                }

                var categories = await _categoryRepository.GetCategoryList();
                var suppliers = await _supplierRepository.GetSupplierList();
                var categoriesList = new SelectList(categories.ToDictionary(cate => cate.CategoryId, cate => cate.CategoryName), "Key", "Value");
                var supplierList = new SelectList(suppliers.ToDictionary(sup => sup.SupplierId, sup => sup.SupplierName), "Key", "Value");

                ViewBag.Category = categoriesList;
                ViewBag.Supplier = supplierList;
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
            return View();
        }

        // POST: FlowerBouquet/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FlowerBouquetId,CategoryId,FlowerBouquetName,Description,UnitPrice,UnitsInStock,FlowerBouquetStatus,SupplierId")] FlowerBouquet flowerBouquet)
        {
            try
            {
                ValidationResult rs = await _validation.ValidateAsync(flowerBouquet);
                if (!rs.IsValid)
                {
                    rs.AddToModelState(this.ModelState);
                    TempData["Errors"] = rs.Errors.Select(e => e.ErrorMessage).ToArray();
                    return RedirectToAction("Create");
                }
                    await _flowerBouquetRepository.Add(flowerBouquet);
                    await _signalHub.Clients.All.SendAsync("LoadFlowerBouquets");
                    return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Create");
            }
        }

        // GET: FlowerBouquet/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                string userLogin = HttpContext.Session.GetString("USERLOGIN");
                if (!(await _customerRepository.IsAdmin(userLogin)))
                {
                    return RedirectToAction("Index", "User");
                }
                FlowerBouquet flowerBouquet = await _flowerBouquetRepository.GetFlowerBouquetById(id);
                if (flowerBouquet is null)
                {
                    throw new Exception("FlowerBouquet ID is not found!!!");
                }
                var categories = await _categoryRepository.GetCategoryList();
                var suppliers = await _supplierRepository.GetSupplierList();
                var categoriesList = new SelectList(categories.ToDictionary(cate => cate.CategoryId, cate => cate.CategoryName), "Key", "Value");
                var supplierList = new SelectList(suppliers.ToDictionary(sup => sup.SupplierId, sup => sup.SupplierName), "Key", "Value");
                ViewBag.Category = categoriesList;
                ViewBag.Supplier = supplierList;
                return View(flowerBouquet);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: FlowerBouquet/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int FlowerBouquetId, [Bind("FlowerBouquetId,CategoryId,FlowerBouquetName,Description,UnitPrice,UnitsInStock,FlowerBouquetStatus,SupplierId")] FlowerBouquet flowerBouquet)
        {
            try
            {
                ValidationResult rs = await _validation.ValidateAsync(flowerBouquet);
                if (rs.IsValid)
                {
                    await _flowerBouquetRepository.Update(flowerBouquet);
                    await _signalHub.Clients.All.SendAsync("LoadFlowerBouquets");
                    return RedirectToAction(nameof(Index));
                }
                rs.AddToModelState(this.ModelState);
                return View("Edit", flowerBouquet);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Edit");
            }
        }

        // GET: FlowerBouquet/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                string userLogin = HttpContext.Session.GetString("USERLOGIN");
                if (!(await _customerRepository.IsAdmin(userLogin)))
                {
                    return RedirectToAction("Index", "User");
                }
                if (await _flowerBouquetRepository.GetFlowerBouquetById(id) is null)
                {
                    return NotFound();
                }
                var flowerBouquet = await _flowerBouquetRepository.GetFlowerBouquetById(id);
                if (flowerBouquet is null)
                {
                    throw new Exception("FlowerBouquet ID is not found!!!");
                }
                return View(flowerBouquet);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: FlowerBouquet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int FlowerBouquetId)
        {
            if (await _flowerBouquetRepository.GetFlowerBouquetById(FlowerBouquetId) is null)
            {
                return Problem("Entity set 'FuflowerBouquetManagementContext.FlowerBouquets'  is null.");
            }
            var flowerBouquet = await _flowerBouquetRepository.GetFlowerBouquetById(FlowerBouquetId);
            if (flowerBouquet is not null)
            {

NguyenManhToan_SE1604_A02/Controllers/UserController.cs
using BusinessObjects.Entities;
using Microsoft.AspNetCore.Mvc;
using Repositories.IRepositories;

namespace NguyenManhToan_SE1604_A02.Controllers
{
    public class UserController : BaseController
    {
        public UserController(ICustomerRepository customerRepository, IOrderRepository orderRepository, IOrderDetailRepository orderDetailRepository, IFlowerBouquetRepository flowerBouquetRepository, ICategoryRepository categoryRepository, ISupplierRepository supplierRepository) : base(customerRepository, orderRepository, orderDetailRepository, flowerBouquetRepository, categoryRepository, supplierRepository)
        {
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            try
            {
                Customer result = await _customerRepository.Login(email, password);
                
                if (result.CustomerName is "Admin")
                {
                    HttpContext.Session.SetString("USERLOGIN", result.Email);
                    return RedirectToAction("Index","Admin");
                }
                else
                {
                    HttpContext.Session.SetString("USERLOGIN", result.Email);
                    HttpContext.Session.SetString("CustomerId", result.CustomerId.ToString());
                    return RedirectToAction("ViewProfile", "Customer");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("Index");
            }

        }
    }
}

NguyenManhToan_SE1604_A02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/home.css" rel="stylesheet" />
    <!-- gLightbox gallery-->
    <link rel="stylesheet" href="~/vendor/glightbox/css/glightbox.min.css">
    <!-- Range slider-->
    <link rel="stylesheet" href="~/vendor/nouislider/nouislider.min.css">
    <!-- Choices CSS-->
    <link rel="stylesheet" href="~/vendor/choices.js/public/assets/styles/choices.min.css">
    <!-- Swiper slider-->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/vendor/swiper/swiper-bundle.min.css">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/img/favicon.png">
    <link rel="stylesheet" href="~/NguyenManhToan_SE1604_A02.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="navbar">
            <div class="inner-width">
                <a href="#" class="logo">Flower Bouquet</a>
                <div class="navbar-menu">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">home</a>
                    <a href="#" class="nav-link">about</a>
                    <a asp-controller="FlowerBouquet" asp-action="Index" class="nav-link">FlowerBouquet</a>
                    <a href="#" class="nav-link">contact</a>
                    <a class="nav-link" asp-controller="Cart" asp-action="Index"> <i class="fas fa-dolly-flatbed me-1 text-gray"></i>Cart</a>
                    <a class="nav-link" asp-controller="User" asp-action="Index"> <i class="fas fa-user me-1 text-gray fw-normal"></i>Login</a>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @*<footer style="background-color:#EEDCBA;color:black">
    <div class="container py-4">
    <div class="row py-5">
    <div class="col-md-4 mb-3 mb-md-0">
    <h6 class="text-uppercase mb-3">Customer Services</h6>
    <ul class="list-unstyled mb-0">
    <li><a class="footer-link" href="#!">Help &amp; Contact Us</a></li>
    <li><a class="footer-link" href="#!">Returns &amp; Refunds</a></li>
    <li><a class="footer-link" href="#!">Online Stores</a></li>
    <li><a class="footer-link" href="#!">Terms &amp; Conditions</a></li>
    </ul>
    </div>
    <div class="col-md-4 mb-3 mb-md-0">
    <h6 class="text-uppercase mb-3">Company</h6>
    <ul class="list-unstyled mb-0">
    <li><a class="footer-link" href="#!">What We Do</a></li>
    <li><a class="footer-link" href="#!">Available Services</a></li>
    <li><a class="footer-link" href="#!">Latest Posts</a></li>
    <li><a class="footer-link" href="#!">FAQs</a></li>
    </ul>
    </div>
    <div class="col-md-4">
    <h6 class="text-uppercase mb-3">Social Media</h6>
    <ul class="list-unstyled mb-0">
    <li><a class="footer-link" href="#!">Twitter</a></li>
    <li><a class="footer-link" href="#!">Instagram</a></li>
    <li><a class="footer-link" href="#!">Tumblr</a></li>
    <li><a class="footer-link" href="#!">Pinterest</a></li>
    </ul>
    </div>
    </div>
    <div class="border-top pt-4" style="border-color: #9a533d;">
    <div class="row">
    <div class="col-md-6 text-center text-md-start">
    <p class="small text-muted mb-0">&copy; 2023 All rights reserved.</p>
    </div>
    </div>
    </div>
    </div>
    </footer>*@
    @*<footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2023 - Flower Bouquet
    </div>
    </footer>*@
    <!-- JavaScript files-->
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="vendor/glightbox/js/glightbox.min.js"></script>
    <script src="vendor/nouislider/nouislider.min.js"></script>
    <script src="vendor/swiper/swiper-bundle.min.js"></script>
    <script src="vendor/choices.js/public/assets/scripts/choices.min.js"></script>
    <script src="js/front.js"></script>
    <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite -
        //   see more here
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {

            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function (e) {
                var div = document.createElement("div");
                div.className = 'd-none';
                div.innerHTML = ajax.responseText;
                document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg');

    </script>
    <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
    <script src="~/js/site.js"></script>
    <script src="~/microsoft/signalr/dist/browser/signalr.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>