NguyenManhToan_SE1604_A03/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Repositories.IRepositories;

namespace NguyenManhToan_SE1604_A02.Controllers
{
    public class LogoutController:BaseController
    {
        public LogoutController(ICustomerRepository customerRepository, IOrderRepository orderRepository, IOrderDetailRepository orderDetailRepository, IFlowerBouquetRepository flowerBouquetRepository, ICategoryRepository categoryRepository, ISupplierRepository supplierRepository) : base(customerRepository, orderRepository, orderDetailRepository, flowerBouquetRepository, categoryRepository, supplierRepository)
        {
        }

        public IActionResult Index()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "User");
        }
    }
}

NguyenManhToan_SE1604_A03/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObjects.Entities;
using Repositories.IRepositories;
using FluentValidation;
using FluentValidation.Results;
using FluentValidation.AspNetCore;

namespace NguyenManhToan_SE1604_A02.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IValidator<Order> _validation;

        public OrderController(ICustomerRepository customerRepository, IOrderRepository orderRepository, IOrderDetailRepository orderDetailRepository, IFlowerBouquetRepository flowerBouquetRepository, ICategoryRepository categoryRepository, ISupplierRepository supplierRepository, IValidator<Order> validation) : base(customerRepository, orderRepository, orderDetailRepository, flowerBouquetRepository, categoryRepository, supplierRepository)
        {
            _validation = validation;
        }
        // GET: Order
        public async Task<IActionResult> Index()
        {
            string userLogin = HttpContext.Session.GetString("USERLOGIN");
            if (!(await _customerRepository.IsLogin(userLogin)))
            {
                return RedirectToAction("Index", "User");
            }
            var orders = await _orderRepository.GetAll();
            return orders is not null ?
                        View(orders.ToList()) :
                        Problem("Entity set 'FuflowerBouquetManagementContext.Orders'  is null.");
        }

        // GET: Order/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                string userLogin = HttpContext.Session.GetString("USERLOGIN");
                if (!(await _customerRepository.IsAdmin(userLogin)))
                {
                    return RedirectToAction("Index", "User");
                }
                if (await _orderRepository.GetById(id) is null)
                {
                    throw new Exception("Order ID is not found!!!");
                }
                var order = await _orderRepository.GetById(id);
                if (order is null)
                {
                    throw new Exception("Order ID is not found!!!");
                }
                return View(order);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: Order/Create
        public async Task<IActionResult> Create()
        {
            try
            {
                string userLogin = HttpContext.Session.GetString("USERLOGIN");
                if (!(await _customerRepository.IsAdmin(userLogin)))
                {
                    return RedirectToAction("Index", "User");
                }
                var customer = await _customerRepository.GetAllCustomer();
                var customerList = new SelectList(customer.ToDictionary(x => x.CustomerId, x => x.CustomerName), "Key", "Value");
                ViewBag.Customer = customerList;
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
            return View();
        }

        // POST: Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,CustomerId,OrderDate,ShippedDate,Total,OrderStatus")] Order order)
        {
            try
            {
                //if (ModelState.IsValid)
                //{
                ValidationResult rs = await _validation.ValidateAsync(order);
                if (rs.IsValid)
                {
                    await _orderRepository.Add(order);
                    return RedirectToAction(nameof(Index));
                }
                rs.AddToModelState(this.ModelState);
                return View("Create", order);
                //}
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Create");
            }
            //return null;
        }

        // GET: Order/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                string userLogin = HttpContext.Session.GetString("USERLOGIN");
                if (!(await _customerRepository.IsAdmin(userLogin)))
                {
                    return RedirectToAction("Index", "User");
                }
                var order = await _orderRepository.GetById(id);
                if (order is null)
                {
                    throw new Exception("Order ID is not found!!!");
                }
                var customer = await _customerRepository.GetAllCustomer();
                var customerList = new SelectList(customer.ToDictionary(x => x.CustomerId, x => x.CustomerName), "Key", "Value");
                ViewBag.Customer = customerList;
                return View(order);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: Order/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,CustomerId,OrderDate,ShippedDate,Total,OrderStatus")] Order order)
        {
            return View();
        }

        // GET: Order/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                string userLogin = HttpContext.Session.GetString("USERLOGIN");
                if (!(await _customerRepository.IsAdmin(userLogin)))
                {
                    return RedirectToAction("Index", "User");
                }
                if (await _orderRepository.GetById(id) is null)
                {
                    return NotFound();
                }
                var order = await _orderRepository.GetById(id);
                if (order is null)
                {
                    throw new Exception("Order ID is not found!!!");
                }
                return View(order);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _orderRepository.GetById(id) is null)
            {
                return Problem("Entity set 'FuflowerBouquetManagementContext.Orders'  is null.");
            }
            var order = await _orderRepository.GetById(id);
            if (order is not null)
            {
                await _orderRepository.DeleteByID(order.OrderId);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

NguyenManhToan_SE1604_A03/Views/Admin/Index.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand mb-0 h1" href="#">Welcome Admin!</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Logout">Logout</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Manage
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        <li><a class="dropdown-item" asp-controller="Customer" asp-action="Index">Customer</a></li>
                        <li><a class="dropdown-item" asp-controller="FlowerBouquet" asp-action="Index">FlowerBouquet</a></li>
                        <li><a class="dropdown-item" asp-controller="Order" asp-action="Index">Order</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Link</a>
                </li>
            </ul>
        </div>
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
             <p>
                @if (ViewBag.Error is not null)
                {
                        <div class="text-danger">
                        @ViewBag.Error
                        </div>
                }
            </p>
    </div>
</nav>